Repository src-d/go-git, pull requests merged in 2018-08, with the labels that each got.

#906 Improve packfile reading performance
  common_test.go
  plumbing/format/idxfile/decoder.go
  plumbing/format/idxfile/decoder_test.go
  plumbing/format/idxfile/encoder.go
  plumbing/format/idxfile/encoder_test.go
  plumbing/format/idxfile/idxfile.go
  plumbing/format/idxfile/idxfile_test.go
  plumbing/format/idxfile/writer.go
  plumbing/format/idxfile/writer_test.go
  plumbing/format/packfile/common.go
  plumbing/format/packfile/decoder.go
  plumbing/format/packfile/decoder_test.go
  plumbing/format/packfile/encoder_advanced_test.go
  plumbing/format/packfile/encoder_test.go
  plumbing/format/packfile/fsobject.go
  plumbing/format/packfile/index.go
  plumbing/format/packfile/index_test.go
  plumbing/format/packfile/packfile.go
  plumbing/format/packfile/packfile_test.go
  plumbing/format/packfile/parser.go
  plumbing/format/packfile/parser_test.go
  plumbing/format/packfile/patch_delta.go
  plumbing/memory.go
  plumbing/object/blob_test.go
  plumbing/object/difftree_test.go
  plumbing/object/object_test.go
  plumbing/transport/test/receive_pack.go
  plumbing/transport/test/upload_pack.go
  repository_test.go
  storage/filesystem/dotgit/dotgit.go
  storage/filesystem/dotgit/writers.go
  storage/filesystem/dotgit/writers_test.go
  storage/filesystem/object.go
  storage/filesystem/object_test.go
Labels: performance

#921 plumbing/object: fix panic when reading object header
  plumbing/object/commit.go
  plumbing/object/commit_test.go
Labels: bug

#887 added support for quarantine directory
  storage/filesystem/dotgit/dotgit.go
  storage/filesystem/dotgit/dotgit_test.go
Labels: enhancement
